In [29]:
from tensorflow.keras.preprocessing.text import one_hot

In [30]:
# Sentences
sent=[ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [31]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [32]:
# Define the vocabulary size 
voc_size=10000

In [33]:
# One Hot Representation 
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3381, 3984, 240, 875],
 [3381, 3984, 240, 4402],
 [3381, 8992, 240, 6728],
 [632, 7864, 3273, 3683, 9883],
 [632, 7864, 3273, 3683, 5912],
 [7629, 3381, 159, 240, 9592],
 [6266, 6990, 5164, 3683]]

In [34]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [35]:
import numpy as np

In [36]:
# Making each sentences of equal size using pad_sequences, below function using pre as value in padding which indicates that add 0 at the place where there is empty, and we had given the maz length of padding 
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3381 3984  240  875]
 [   0    0    0    0 3381 3984  240 4402]
 [   0    0    0    0 3381 8992  240 6728]
 [   0    0    0  632 7864 3273 3683 9883]
 [   0    0    0  632 7864 3273 3683 5912]
 [   0    0    0 7629 3381  159  240 9592]
 [   0    0    0    0 6266 6990 5164 3683]]


In [37]:
# Feature representation 
dim=10

In [43]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [45]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (8, 10)                │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 379ms/step


array([[[-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [ 1.76920630e-02, -5.84338978e-03,  4.84342612e-02,
         -1.42258629e-02,  1.76948644e-02, -1.08544715e-02,
         -3.59355919e-02, -2.64011323e-04,  4.497550

In [41]:
embedded_docs[0]

array([   0,    0,    0,    0, 3381, 3984,  240,  875], dtype=int32)

In [44]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step


array([[-0.03892752,  0.02122349, -0.02359991, -0.03021014,  0.04754355,
         0.00647074,  0.01121308,  0.03020468, -0.04457123,  0.00853959],
       [-0.03892752,  0.02122349, -0.02359991, -0.03021014,  0.04754355,
         0.00647074,  0.01121308,  0.03020468, -0.04457123,  0.00853959],
       [-0.03892752,  0.02122349, -0.02359991, -0.03021014,  0.04754355,
         0.00647074,  0.01121308,  0.03020468, -0.04457123,  0.00853959],
       [-0.03892752,  0.02122349, -0.02359991, -0.03021014,  0.04754355,
         0.00647074,  0.01121308,  0.03020468, -0.04457123,  0.00853959],
       [-0.01895726, -0.00426165,  0.03493853, -0.02564912,  0.03624951,
        -0.0244468 ,  0.01395399,  0.03794036,  0.04156688,  0.03211028],
       [ 0.01373197,  0.04251922,  0.04110948, -0.01431838, -0.04397181,
        -0.03497596,  0.00574919, -0.0481659 , -0.04424905,  0.0261247 ],
       [-0.0432958 , -0.04016887, -0.02226696,  0.00602179, -0.00200161,
        -0.03925198, -0.00398447, -0.04704471