In [29]:
from tensorflow.keras.preprocessing.text import one_hot

In [30]:
# Sentences
sent=[ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [31]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [32]:
# Define the vocabulary size 
voc_size=10000

In [33]:
# One Hot Representation 
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3381, 3984, 240, 875],
 [3381, 3984, 240, 4402],
 [3381, 8992, 240, 6728],
 [632, 7864, 3273, 3683, 9883],
 [632, 7864, 3273, 3683, 5912],
 [7629, 3381, 159, 240, 9592],
 [6266, 6990, 5164, 3683]]

In [34]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [35]:
import numpy as np

In [36]:
# Making each sentences of equal size using pad_sequences, below function using pre as value in padding which indicates that add 0 at the place where there is empty, and we had given the maz length of padding 
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3381 3984  240  875]
 [   0    0    0    0 3381 3984  240 4402]
 [   0    0    0    0 3381 8992  240 6728]
 [   0    0    0  632 7864 3273 3683 9883]
 [   0    0    0  632 7864 3273 3683 5912]
 [   0    0    0 7629 3381  159  240 9592]
 [   0    0    0    0 6266 6990 5164 3683]]


In [37]:
# Feature representation 
dim=10

In [38]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [39]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 379ms/step


array([[[-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [-3.05915717e-02, -2.95140278e-02,  4.93585952e-02,
         -4.64825295e-02, -5.63107431e-04, -4.17497009e-03,
         -4.10524383e-02,  4.05931957e-02,  1.82007216e-02,
          1.04708448e-02],
        [ 1.76920630e-02, -5.84338978e-03,  4.84342612e-02,
         -1.42258629e-02,  1.76948644e-02, -1.08544715e-02,
         -3.59355919e-02, -2.64011323e-04,  4.497550

In [41]:
embedded_docs[0]

array([   0,    0,    0,    0, 3381, 3984,  240,  875], dtype=int32)

In [42]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>