In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent=[ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size 
voc_size=10000

In [5]:
# One Hot Representation 
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5346, 9297, 6309, 9831],
 [5346, 9297, 6309, 6452],
 [5346, 5190, 6309, 6669],
 [964, 5456, 598, 5710, 8153],
 [964, 5456, 598, 5710, 6556],
 [9593, 5346, 2494, 6309, 9215],
 [4954, 5918, 1484, 5710]]

In [6]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
# Making each sentences of equal size using pad_sequences, below function using pre as value in padding which indicates that add 0 at the place where there is empty, and we had given the maz length of padding 
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5346 9297 6309 9831]
 [   0    0    0    0 5346 9297 6309 6452]
 [   0    0    0    0 5346 5190 6309 6669]
 [   0    0    0  964 5456  598 5710 8153]
 [   0    0    0  964 5456  598 5710 6556]
 [   0    0    0 9593 5346 2494 6309 9215]
 [   0    0    0    0 4954 5918 1484 5710]]


In [9]:
# Feature representation 
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\AYAN SONI\Desktop\Deep Learning NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step


array([[[-4.42751497e-03, -2.95634624e-02, -4.51143757e-02,
         -4.41181324e-02, -9.94239002e-03,  3.79945971e-02,
          2.58795917e-05, -1.42510980e-03, -2.87400968e-02,
         -7.44650513e-03],
        [-4.42751497e-03, -2.95634624e-02, -4.51143757e-02,
         -4.41181324e-02, -9.94239002e-03,  3.79945971e-02,
          2.58795917e-05, -1.42510980e-03, -2.87400968e-02,
         -7.44650513e-03],
        [-4.42751497e-03, -2.95634624e-02, -4.51143757e-02,
         -4.41181324e-02, -9.94239002e-03,  3.79945971e-02,
          2.58795917e-05, -1.42510980e-03, -2.87400968e-02,
         -7.44650513e-03],
        [-4.42751497e-03, -2.95634624e-02, -4.51143757e-02,
         -4.41181324e-02, -9.94239002e-03,  3.79945971e-02,
          2.58795917e-05, -1.42510980e-03, -2.87400968e-02,
         -7.44650513e-03],
        [ 3.36278342e-02, -2.28796136e-02,  3.53139080e-02,
         -4.59678099e-03,  4.99892496e-02,  1.95642151e-02,
         -4.29583453e-02, -3.53021547e-03, -1.882958

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 5346, 9297, 6309, 9831], dtype=int32)