In [15]:
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
# Sentences
sent=[ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [17]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
# Define the vocabulary size 
voc_size=10000

In [19]:
# One Hot Representation 
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3381, 3984, 240, 875],
 [3381, 3984, 240, 4402],
 [3381, 8992, 240, 6728],
 [632, 7864, 3273, 3683, 9883],
 [632, 7864, 3273, 3683, 5912],
 [7629, 3381, 159, 240, 9592],
 [6266, 6990, 5164, 3683]]

In [20]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [21]:
import numpy as np

In [22]:
# Making each sentences of equal size using pad_sequences, below function using pre as value in padding which indicates that add 0 at the place where there is empty, and we had given the maz length of padding 
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3381 3984  240  875]
 [   0    0    0    0 3381 3984  240 4402]
 [   0    0    0    0 3381 8992  240 6728]
 [   0    0    0  632 7864 3273 3683 9883]
 [   0    0    0  632 7864 3273 3683 5912]
 [   0    0    0 7629 3381  159  240 9592]
 [   0    0    0    0 6266 6990 5164 3683]]


In [23]:
# Feature representation 
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 225ms/step


array([[[-0.02731137, -0.04886572,  0.00611776,  0.0244293 ,
         -0.02397467,  0.04164973,  0.01531646, -0.01274367,
          0.01682817,  0.00872601],
        [-0.02731137, -0.04886572,  0.00611776,  0.0244293 ,
         -0.02397467,  0.04164973,  0.01531646, -0.01274367,
          0.01682817,  0.00872601],
        [-0.02731137, -0.04886572,  0.00611776,  0.0244293 ,
         -0.02397467,  0.04164973,  0.01531646, -0.01274367,
          0.01682817,  0.00872601],
        [-0.02731137, -0.04886572,  0.00611776,  0.0244293 ,
         -0.02397467,  0.04164973,  0.01531646, -0.01274367,
          0.01682817,  0.00872601],
        [-0.02563779, -0.04712051,  0.04909862,  0.00648513,
          0.03748626, -0.03226961, -0.01488721, -0.04770104,
         -0.02083962,  0.04250623],
        [ 0.01503364,  0.010489  , -0.00877611,  0.04366204,
         -0.02377951,  0.00230523,  0.01441569,  0.04911007,
         -0.02746317, -0.00317015],
        [-0.00283601, -0.03189465, -0.02679726, -0.0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 3381, 3984,  240,  875], dtype=int32)

In [28]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step


array([[-2.20409986e-02,  4.41661812e-02, -4.02765386e-02,
        -9.97594744e-03, -4.30166498e-02,  1.85028948e-02,
         9.10787657e-03, -3.69886383e-02,  8.60289484e-03,
         4.49511744e-02],
       [-2.20409986e-02,  4.41661812e-02, -4.02765386e-02,
        -9.97594744e-03, -4.30166498e-02,  1.85028948e-02,
         9.10787657e-03, -3.69886383e-02,  8.60289484e-03,
         4.49511744e-02],
       [-2.20409986e-02,  4.41661812e-02, -4.02765386e-02,
        -9.97594744e-03, -4.30166498e-02,  1.85028948e-02,
         9.10787657e-03, -3.69886383e-02,  8.60289484e-03,
         4.49511744e-02],
       [-2.20409986e-02,  4.41661812e-02, -4.02765386e-02,
        -9.97594744e-03, -4.30166498e-02,  1.85028948e-02,
         9.10787657e-03, -3.69886383e-02,  8.60289484e-03,
         4.49511744e-02],
       [-4.59164158e-02,  1.58904865e-03, -9.09939408e-05,
        -1.38575919e-02,  1.14805624e-03, -3.66970301e-02,
        -1.90787911e-02,  2.70880572e-02,  4.33668159e-02,
        -7.