In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences
sent=[ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent 

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size 
voc_size=10000

In [5]:
# One Hot Representation 
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3157, 9766, 8116, 8085],
 [3157, 9766, 8116, 8603],
 [3157, 4535, 8116, 6559],
 [9735, 4637, 4596, 7772, 1300],
 [9735, 4637, 4596, 7772, 7866],
 [1005, 3157, 7155, 8116, 5204],
 [8722, 9174, 916, 7772]]

In [6]:
# Word Embedding Representation

from tensorflow.keras.layers import Embedding 
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [18]:
# Making each sentences of equal size using pad_sequences, below function using pre as value in padding which indicates that add 0 at the place where there is empty, and we had given the maz length of padding 
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3157 9766 8116 8085]
 [   0    0    0    0 3157 9766 8116 8603]
 [   0    0    0    0 3157 4535 8116 6559]
 [   0    0    0 9735 4637 4596 7772 1300]
 [   0    0    0 9735 4637 4596 7772 7866]
 [   0    0    0 1005 3157 7155 8116 5204]
 [   0    0    0    0 8722 9174  916 7772]]


In [9]:
# Feature representation 
dim=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step


array([[[ 0.02624503,  0.01554776, -0.01658914,  0.0481995 ,
         -0.01369377, -0.02775635, -0.00564951, -0.03353832,
         -0.04322867,  0.04158619],
        [ 0.02624503,  0.01554776, -0.01658914,  0.0481995 ,
         -0.01369377, -0.02775635, -0.00564951, -0.03353832,
         -0.04322867,  0.04158619],
        [ 0.02624503,  0.01554776, -0.01658914,  0.0481995 ,
         -0.01369377, -0.02775635, -0.00564951, -0.03353832,
         -0.04322867,  0.04158619],
        [ 0.02624503,  0.01554776, -0.01658914,  0.0481995 ,
         -0.01369377, -0.02775635, -0.00564951, -0.03353832,
         -0.04322867,  0.04158619],
        [ 0.01048847, -0.04482215, -0.04871407, -0.02831637,
          0.00081296, -0.03575433,  0.02456533,  0.03854078,
          0.02559746, -0.01288719],
        [-0.04162314,  0.00277216,  0.01837167,  0.03444961,
          0.01494079, -0.02315599,  0.02120327,  0.01380194,
         -0.04287816, -0.04918101],
        [ 0.04723981, -0.0138816 , -0.01893395, -0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 3157, 9766, 8116, 8085], dtype=int32)

In [26]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step


array([[-0.02237782,  0.001905  , -0.02293421,  0.02226741, -0.03492025,
         0.03524959, -0.02260096, -0.04226397, -0.02433896, -0.03587605],
       [-0.02237782,  0.001905  , -0.02293421,  0.02226741, -0.03492025,
         0.03524959, -0.02260096, -0.04226397, -0.02433896, -0.03587605],
       [-0.02237782,  0.001905  , -0.02293421,  0.02226741, -0.03492025,
         0.03524959, -0.02260096, -0.04226397, -0.02433896, -0.03587605],
       [-0.02237782,  0.001905  , -0.02293421,  0.02226741, -0.03492025,
         0.03524959, -0.02260096, -0.04226397, -0.02433896, -0.03587605],
       [ 0.00173013,  0.00919918, -0.02798691,  0.02209128,  0.02223626,
         0.01255627,  0.02466187,  0.02936414,  0.01396101, -0.02439911],
       [-0.00088907,  0.03515783, -0.0498342 ,  0.0366701 ,  0.03678072,
        -0.00069191,  0.02075842,  0.0327897 ,  0.03888364,  0.03932785],
       [ 0.0102729 ,  0.04963071, -0.02889235,  0.03793104,  0.03645689,
        -0.02634974, -0.00315676,  0.04712984